name: pyt
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8
  - pip
  - matplotlib
  - numpy
  - scipy
  - control
  - pydot
  - autopep8
  - pytest
  - pylint
  - jupyterlab
  - ffmpeg
  - openh264
  - pandas
  - JSAnimation
  - pip:
    - casadi
    - torch
    - torchvision
    - gym
