/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_gen_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};

/* state_from_gz:(x_gz[12])->(x[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][8] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][7] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][0] : 0;
  a6=(a4*a5);
  a7=sin(a2);
  a1=(a1*a7);
  a8=arg[0]? arg[0][6] : 0;
  a9=sin(a8);
  a10=(a1*a9);
  a11=sin(a0);
  a12=cos(a8);
  a13=(a11*a12);
  a10=(a10-a13);
  a13=arg[0]? arg[0][1] : 0;
  a14=(a10*a13);
  a6=(a6+a14);
  a14=sin(a8);
  a11=(a11*a14);
  a15=cos(a8);
  a1=(a1*a15);
  a11=(a11+a1);
  a1=arg[0]? arg[0][2] : 0;
  a16=(a11*a1);
  a6=(a6+a16);
  if (res[0]!=0) res[0][0]=a6;
  a6=sin(a0);
  a3=(a6*a3);
  a16=(a3*a5);
  a17=cos(a0);
  a12=(a17*a12);
  a6=(a6*a7);
  a7=(a6*a9);
  a12=(a12+a7);
  a7=(a12*a13);
  a16=(a16+a7);
  a6=(a6*a15);
  a17=(a17*a14);
  a6=(a6-a17);
  a17=(a6*a1);
  a16=(a16+a17);
  if (res[0]!=0) res[0][1]=a16;
  a16=cos(a2);
  a9=(a16*a9);
  a13=(a9*a13);
  a17=sin(a2);
  a5=(a17*a5);
  a13=(a13-a5);
  a16=(a16*a15);
  a1=(a16*a1);
  a13=(a13+a1);
  if (res[0]!=0) res[0][2]=a13;
  a13=arg[0]? arg[0][3] : 0;
  a4=(a4*a13);
  a1=arg[0]? arg[0][4] : 0;
  a10=(a10*a1);
  a4=(a4+a10);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a11*a10);
  a4=(a4+a11);
  if (res[0]!=0) res[0][3]=a4;
  a3=(a3*a13);
  a12=(a12*a1);
  a3=(a3+a12);
  a6=(a6*a10);
  a3=(a3+a6);
  if (res[0]!=0) res[0][4]=a3;
  a9=(a9*a1);
  a17=(a17*a13);
  a9=(a9-a17);
  a16=(a16*a10);
  a9=(a9+a16);
  if (res[0]!=0) res[0][5]=a9;
  if (res[0]!=0) res[0][6]=a8;
  if (res[0]!=0) res[0][7]=a2;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int state_from_gz(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int state_from_gz_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int state_from_gz_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void state_from_gz_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int state_from_gz_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void state_from_gz_release(int mem) {
}

CASADI_SYMBOL_EXPORT void state_from_gz_incref(void) {
}

CASADI_SYMBOL_EXPORT void state_from_gz_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int state_from_gz_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int state_from_gz_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real state_from_gz_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* state_from_gz_name_in(casadi_int i){
  switch (i) {
    case 0: return "x_gz";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* state_from_gz_name_out(casadi_int i){
  switch (i) {
    case 0: return "x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* state_from_gz_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* state_from_gz_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int state_from_gz_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* state_from_gz_functions(void) {
  static casadi_functions fun = {
    state_from_gz_incref,
    state_from_gz_decref,
    state_from_gz_checkout,
    state_from_gz_release,
    state_from_gz_default_in,
    state_from_gz_n_in,
    state_from_gz_n_out,
    state_from_gz_name_in,
    state_from_gz_name_out,
    state_from_gz_sparsity_in,
    state_from_gz_sparsity_out,
    state_from_gz_work,
    state_from_gz
  };
  return &fun;
}
/* quad_force_moment:(x[12],u_mix[4],p[13])->(F_b[3],M_b[3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][8] : 0;
  a1=sin(a0);
  a2=arg[0]? arg[0][6] : 0;
  a3=sin(a2);
  a1=(a1*a3);
  a4=cos(a0);
  a5=arg[0]? arg[0][7] : 0;
  a6=sin(a5);
  a4=(a4*a6);
  a2=cos(a2);
  a4=(a4*a2);
  a1=(a1+a4);
  a4=arg[2]? arg[2][0] : 0;
  a7=arg[2]? arg[2][8] : 0;
  a4=(a4*a7);
  a1=(a1*a4);
  a1=(-a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=sin(a0);
  a1=(a1*a6);
  a1=(a1*a2);
  a0=cos(a0);
  a0=(a0*a3);
  a1=(a1-a0);
  a1=(a1*a4);
  a1=(-a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[2]? arg[2][6] : 0;
  a0=5.0000000000000000e-01;
  a3=arg[2]? arg[2][3] : 0;
  a6=(a0*a3);
  a7=1.0471975511965977e-01;
  a8=1.;
  a9=2.5000000000000000e-01;
  a10=arg[1]? arg[1][0] : 0;
  a11=(a9*a10);
  a12=-2.5000000000000000e-01;
  a13=arg[1]? arg[1][1] : 0;
  a14=(a12*a13);
  a11=(a11+a14);
  a14=arg[1]? arg[1][2] : 0;
  a15=(a12*a14);
  a11=(a11+a15);
  a15=arg[1]? arg[1][3] : 0;
  a16=(a9*a15);
  a11=(a11+a16);
  a16=(a8<a11);
  a17=(a16?a8:0);
  a16=(!a16);
  a18=0.;
  a19=(a11<a18);
  a19=(!a19);
  a19=(a19?a11:0);
  a16=(a16?a19:0);
  a17=(a17+a16);
  a16=arg[2]? arg[2][4] : 0;
  a17=(a17*a16);
  a19=arg[2]? arg[2][5] : 0;
  a17=(a17*a19);
  a17=(a7*a17);
  a11=arg[2]? arg[2][2] : 0;
  a17=(a17*a11);
  a17=casadi_sq(a17);
  a6=(a6*a17);
  a17=(a1*a6);
  a20=3.1415926535897931e+00;
  a21=casadi_sq(a11);
  a21=(a20*a21);
  a17=(a17*a21);
  a5=cos(a5);
  a5=(a5*a2);
  a5=(a5*a4);
  a5=(a17-a5);
  a4=(a0*a3);
  a2=(a12*a10);
  a22=(a9*a13);
  a2=(a2+a22);
  a22=(a12*a14);
  a2=(a2+a22);
  a22=(a9*a15);
  a2=(a2+a22);
  a22=(a8<a2);
  a23=(a22?a8:0);
  a22=(!a22);
  a24=(a2<a18);
  a24=(!a24);
  a24=(a24?a2:0);
  a22=(a22?a24:0);
  a23=(a23+a22);
  a23=(a23*a16);
  a23=(a23*a19);
  a23=(a7*a23);
  a23=(a23*a11);
  a23=casadi_sq(a23);
  a4=(a4*a23);
  a23=(a1*a4);
  a22=casadi_sq(a11);
  a22=(a20*a22);
  a23=(a23*a22);
  a5=(a5+a23);
  a24=(a0*a3);
  a2=(a12*a10);
  a12=(a12*a13);
  a2=(a2+a12);
  a12=(a9*a14);
  a2=(a2+a12);
  a12=(a9*a15);
  a2=(a2+a12);
  a12=(a8<a2);
  a25=(a12?a8:0);
  a12=(!a12);
  a26=(a2<a18);
  a26=(!a26);
  a26=(a26?a2:0);
  a12=(a12?a26:0);
  a25=(a25+a12);
  a25=(a25*a16);
  a25=(a25*a19);
  a25=(a7*a25);
  a25=(a25*a11);
  a25=casadi_sq(a25);
  a24=(a24*a25);
  a25=(a1*a24);
  a12=casadi_sq(a11);
  a12=(a20*a12);
  a25=(a25*a12);
  a5=(a5+a25);
  a0=(a0*a3);
  a10=(a9*a10);
  a13=(a9*a13);
  a10=(a10+a13);
  a14=(a9*a14);
  a10=(a10+a14);
  a9=(a9*a15);
  a10=(a10+a9);
  a9=(a8<a10);
  a8=(a9?a8:0);
  a9=(!a9);
  a18=(a10<a18);
  a18=(!a18);
  a18=(a18?a10:0);
  a9=(a9?a18:0);
  a8=(a8+a9);
  a8=(a8*a16);
  a8=(a8*a19);
  a7=(a7*a8);
  a7=(a7*a11);
  a7=casadi_sq(a7);
  a0=(a0*a7);
  a1=(a1*a0);
  a11=casadi_sq(a11);
  a20=(a20*a11);
  a1=(a1*a20);
  a5=(a5+a1);
  if (res[0]!=0) res[0][2]=a5;
  a5=7.0710678118654746e-01;
  a11=arg[2]? arg[2][1] : 0;
  a5=(a5*a11);
  a5=(a5*a17);
  a7=-7.0710678118654757e-01;
  a7=(a7*a11);
  a7=(a7*a23);
  a5=(a5+a7);
  a7=-7.0710678118654746e-01;
  a8=(a7*a11);
  a8=(a8*a25);
  a5=(a5+a8);
  a8=7.0710678118654757e-01;
  a19=(a8*a11);
  a19=(a19*a1);
  a5=(a5+a19);
  if (res[1]!=0) res[1][0]=a5;
  a5=(a8*a11);
  a5=(a5*a17);
  a17=(a7*a11);
  a17=(a17*a23);
  a5=(a5+a17);
  a8=(a8*a11);
  a8=(a8*a25);
  a5=(a5+a8);
  a7=(a7*a11);
  a7=(a7*a1);
  a5=(a5+a7);
  a5=(-a5);
  if (res[1]!=0) res[1][1]=a5;
  a5=arg[2]? arg[2][7] : 0;
  a6=(a5*a6);
  a6=(a6*a21);
  a4=(a5*a4);
  a4=(a4*a22);
  a6=(a6+a4);
  a24=(a5*a24);
  a24=(a24*a12);
  a6=(a6-a24);
  a5=(a5*a0);
  a5=(a5*a20);
  a6=(a6-a5);
  if (res[1]!=0) res[1][2]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_force_moment(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_force_moment_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_force_moment_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_force_moment_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_force_moment_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_force_moment_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_force_moment_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_force_moment_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_force_moment_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_force_moment_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quad_force_moment_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_force_moment_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u_mix";
    case 2: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_force_moment_name_out(casadi_int i){
  switch (i) {
    case 0: return "F_b";
    case 1: return "M_b";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_force_moment_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_force_moment_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_force_moment_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* quad_force_moment_functions(void) {
  static casadi_functions fun = {
    quad_force_moment_incref,
    quad_force_moment_decref,
    quad_force_moment_checkout,
    quad_force_moment_release,
    quad_force_moment_default_in,
    quad_force_moment_n_in,
    quad_force_moment_n_out,
    quad_force_moment_name_in,
    quad_force_moment_name_out,
    quad_force_moment_sparsity_in,
    quad_force_moment_sparsity_out,
    quad_force_moment_work,
    quad_force_moment
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
